# Generated by Django 4.2.3 on 2023-07-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("engenheiro_de_dados", "Engenheiro de Dados"),
                            ("cientista_de_dados", "Cientista de Dados"),
                            (
                                "engenheiro_de_machine_learning",
                                "Engenheiro de Machine Learning",
                            ),
                            ("mlops", "MLOps"),
                            ("analista_de_dados", "Analista de Dados"),
                            ("lider_de_equipe", "Líder de Equipe"),
                            ("gerente_de_projetos", "Gerente de Projetos"),
                            (
                                "gerente_de_ciencia_de_dados",
                                "Gerente de Ciência de Dados",
                            ),
                            (
                                "diretor_de_ciencia_de_dados",
                                "Diretor de Ciência de Dados",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("estagiario", "Estagiário"),
                            ("trainee", "Trainee"),
                            ("junior", "Júnior"),
                            ("pleno", "Pleno"),
                            ("senior", "Sênior"),
                            ("especialista", "Especialista"),
                        ],
                        max_length=15,
                    ),
                ),
                ("salario", models.DecimalField(decimal_places=2, max_digits=8)),
                ("data_contratacao", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
